### ISSUE TITLE
Clock font size

### ISSUE THREAD

**Issue by MyrikLD** [Warinyourself/lightdm-webkit-theme-osmos#1]
![изображение](https://user-images.githubusercontent.com/5493841/64535740-795c0a00-d320-11e9-9342-525bb7a075ba.png)
Clock's font size can be too big on screen resolution 1920x1080

**Comment by Warinyourself** [comment]
Странно, потому-что у меня с тем же разрешением текстовое содержимое не вылезает. Вероятно у тебя старая&изменённая версия, потому-что в актуально новой версии тест зеленый + нет розовой кнопки справа снизу.

Где ты отловил подобный баг? (на локалке, gh-page или в aur)

**Comment by MyrikLD** [comment]
Ставил через AUR. Ближайшее время попробую заново перепроверить.

**Comment by MyrikLD** [comment]
Есть еще нюанс: у меня все виснет через секунд 30 после входа на страницу авторизации (если не успеть ввести пароль). Не сталкивался?

**Comment by Warinyourself** [comment]
Вылил обновленную сборку в AUR (если будет ошибка, что не может скачать source - нужно либо удалить кэш пакетного менеджера, либо руками скачать и скомпилоривать пакет с AUR).

Как у тебя выглядит gh-pages (нормальный ли шрифт)?
*На всякий случай поставил :root на 16px, возможно поможет, стоит проверить.

По поводу 30 секунд - нет, самая тяжелая тема это osmos, обычно я использую либо space, либо time - они менее затратные, но даже с osmos нет проблем в том, что через 30 секунд всё виснет. Это у тебя во всех темах или какой-то определенной?
