### ISSUE TITLE
Change the theme name in readme

### ISSUE THREAD

**Issue by vldF** [Warinyourself/lightdm-webkit-theme-osmos#1]
Hello! After the last one update, I got an error: on system boot, I got error with options like: load default theme, fallback theme and do nothing. Also, at this time I saw blank screen

After hours of the bug licating, I got that you changed theme name :)
If I change it in config (in lightdm-webkit2-greeter.conf set webkit_theme = osmos, not webkit_theme = lightdm-webkit-theme-osmos), everything will be fine

**Comment by PoorPocketsMcNewHold** [comment]
I believe the difference between those two, is if you manually install it, by git cloningh the repo in the theme folder, in which, it will indeed have [lightdm-webkit-theme-osmos](https://github.com/Warinyourself/lightdm-webkit-theme-osmos) per the repo name. When you install it via the AUR, it will be installed as osmos *(And it will also edit the lighdm-webkit configuration file accordingly)

**Comment by Warinyourself** [comment]
Thanks for your issue.
I updated the theme name in readme.
And also add hook *post_upgrade* in the PKGBUILD.
