### ISSUE TITLE
Any way to force it to use 1920*1200 ?

### ISSUE THREAD

**Issue by Yocklo** [Warinyourself/lightdm-webkit-theme-osmos#3]
My laptop has a 4k screen and so the animations are pretty laggy, and i know my computer is powerful enough to generate the animations in hd, but right now its almost unusable for me...

**Comment by Warinyourself** [comment]
Hello @Yocklo, I had the same problem but this disappeared when I installed the driver for my GPU.
You can try to install GPU drivers or change the "resolution" slider in the "customize theme" tab.
