### ISSUE TITLE
Blanking after 10 mins.

### ISSUE THREAD

**Issue by mrneilypops** [Warinyourself/lightdm-webkit-theme-osmos#7]
I would like to leave this Arch machine at the login prompt until I enter my password but the login screen blanks after 10 minutes.
I have tried entering consoleblank=0 to the kernel line at boot- no change.

Any ideas how I can do this?

**Comment by Warinyourself** [comment]
Hello, friend, sorry for long response.
I had the same problem, until I settings up nvidia on my computer, maybe this problem actual related with GPU drivers?
