### ISSUE TITLE
osmos not working on manjaro

### ISSUE THREAD

**Issue by zany130** [Warinyourself/lightdm-webkit-theme-osmos#8]
![20200315_200644](https://user-images.githubusercontent.com/25832539/76714335-d33cf280-66fc-11ea-8773-a4dc92070aa4.jpg)
I just get stuck on this screen

**Comment by Warinyourself** [comment]
It strange, because several days ago I tested particular on manjaro. 
So, may you execute this command "lightdm-webkit2-greeter" and send here the output?

**Comment by zany130** [comment]
there it runs and shows correctly
![Screenshot_20200321_213405](https://user-images.githubusercontent.com/25832539/77240407-ccf6bc80-6bbb-11ea-90ca-217eb6a22119.png)

**Comment by Warinyourself** [comment]
That's funny.
Okay, may you send a download manjaro link which you have (for example I has been install manjaro from this [link](https://www.manjaro.org/download/community/openbox/)). I will try track a bug on virtual machine.

**Comment by zany130** [comment]
I'm using manjaro [kde](https://www.manjaro.org/downloads/official/kde/) but I been updating it since last year and I'm also on the testing branch

**Comment by zany130** [comment]
where you able to reproduce the issue?

**Comment by Warinyourself** [comment]
![image](https://user-images.githubusercontent.com/33872448/79012927-342adf80-7b70-11ea-893e-f5982b28dce1.png)
Honestly no, on my virtualbox work fine, maybe reinstall lightdm-webkit2-greeter and lightdm-webkit-theme-osmos may help to resolve this problem?

**Comment by zany130** [comment]
i alread tried reinstalling multiple times. the only thing i can possible think of if its not manjaro then it has to be something specfic with my setup. The only thing in my setup that i can think of that would cause problems is my ultrawide monitor...

**Comment by zany130** [comment]
same issue on vanilla arch installed following the arch wiki
